"""Add travel place coordinates

Revision ID: 63ad418aa07f
Revises: a923profile
Create Date: 2026-09-23 14:43:19.333537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ad418aa07f'
down_revision = 'a923profile'
branch_labels = None
depends_on = None


def upgrade():
    inspector = sa.inspect(op.get_bind())
    if 'travel_places' not in inspector.get_table_names():
        op.create_table(
            'travel_places',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('country', sa.String(100), nullable=False),
            sa.Column('region', sa.String(100), nullable=False),
            sa.Column('place', sa.String(150), nullable=False),
            sa.Column('category', sa.String(100), nullable=False),
            sa.Column('intro', sa.String(100), nullable=False),
            sa.Column('reason', sa.Text(), nullable=False),
            sa.Column('restaurant', sa.Text(), nullable=True),
            sa.Column('nearby', sa.Text(), nullable=True),
            sa.Column('photos', sa.Text(), nullable=True),
            sa.Column('likes', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
        )
    columns = {c['name'] for c in sa.inspect(op.get_bind()).get_columns('travel_places')}
    with op.batch_alter_table('travel_places') as batch_op:
        if 'latitude' not in columns:
            batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        if 'longitude' not in columns:
            batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_places', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
